(function(){
  'use strict';
  var STORAGE='meridian_money_data_v5';
  var CATEGORIES=['Books','Dining & Coffee','Entertainment','Groceries','Health & Fitness','Housing','Insurance','Other','Personal Care','Personal Support','Pets','Service','Shopping','Subscriptions','Transportation','Travel','Utilities'];
  var rules=[
    ['Groceries',/\b(milk|bread|egg|cheese|fruit|apple|banana|berry|vegetable|lettuce|meat|beef|chicken|pork|rice|pasta|cereal|yogurt|coffee|tea|juice|water|snack|cookie|chips|grocery|produce|frozen|sauce|flour|sugar)\b/i],
    ['Dining & Coffee',/\b(burger|sandwich|pizza|latte|mocha|espresso|meal|combo|restaurant|cafe|tip)\b/i],
    ['Transportation',/\b(gas|fuel|oil change|parking|tire|auto|car wash|uber|lyft)\b/i],
    ['Personal Care',/\b(shampoo|conditioner|soap|deodorant|tooth|lotion|cosmetic|makeup|hair|razor)\b/i],
    ['Health & Fitness',/\b(medicine|pharmacy|vitamin|supplement|protein|prescription|medical|fitness|gym)\b/i],
    ['Pets',/\b(pet|dog|cat|litter|kibble|veterinary|vet)\b/i],
    ['Books',/\b(book|magazine|paperback|hardcover|kindle)\b/i],
    ['Entertainment',/\b(movie|game|ticket|music|toy)\b/i],
    ['Utilities',/\b(electric|power|water service|internet|phone service|utility)\b/i],
    ['Housing',/\b(rent|mortgage|home repair|hardware|lumber|paint)\b/i],
    ['Shopping',/\b(clothing|shirt|pants|shoe|jacket|dress|household|decor|electronics)\b/i]
  ];
  function categoryFor(name){var text=String(name||'');if(/\b(walmart|costco|winco|albertsons|kroger|safeway|trader joe|whole foods)\b/i.test(text))return'Groceries';if(/\b(starbucks|mcdonald|wendy|subway|restaurant|cafe|grill)\b/i.test(text))return'Dining & Coffee';if(/\b(shell|chevron|exxon|sinclair|maverik|gas station)\b/i.test(text))return'Transportation';if(/\b(walgreens|cvs|rite aid|pharmacy)\b/i.test(text))return'Health & Fitness';for(var i=0;i<rules.length;i++)if(rules[i][1].test(text))return rules[i][0];return'Shopping';}
  function money(v){var n=Number(String(v||'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?Math.abs(n):0;}
  function parseReceipt(text){
    var rows=[],lines=String(text||'').split(/\r?\n/).map(function(x){return x.replace(/\s+/g,' ').trim();}).filter(Boolean);
    lines.forEach(function(line){
      var m=line.match(/^(.*?)(?:\s{1,}|\.{2,})\$?(-?\d{1,4}\s*[.,]\s*\d{2})\s*[A-Z]?$|^(.*?)\s+\$?(\d{1,4})\s+(\d{2})$/i);
      if(!m)return;var name=(m[1]||m[3]||'').replace(/^[*#-]+|\s+[A-Z]$/g,'').trim(),price=money(String(m[2]||(m[4]+'.'+m[5])).replace(/\s/g,'').replace(',','.'));
      if(!name||!price||/\b(sub\s*total|total|balance|cash|change|credit|debit|visa|mastercard|amount due|tender)\b/i.test(name))return;
      rows.push({name:name,price:price,category:/\b(tax)\b/i.test(name)?'Other':categoryFor(name)});
    });
    if(!rows.length){
      lines.forEach(function(line){var prices=line.match(/\$?\d{1,4}[.,]\d{2}/g);if(!prices||prices.length!==1)return;var price=money(prices[0].replace(',','.')),name=line.replace(prices[0],'').replace(/[^A-Za-z0-9 &'/-]/g,' ').replace(/\s+/g,' ').trim();if(name.length>1&&price&&!/\b(total|balance|tender|change|cash|credit|debit)\b/i.test(name))rows.push({name:name,price:price,category:categoryFor(name)});});
    }
    return rows;
  }
  function readData(){try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')||{};}catch(e){return{};}}
  function uid(){return Math.random().toString(36).slice(2,10)+Date.now().toString(36).slice(-4);}
  function today(){var d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,10);}
  function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]);});}
  function receiptTotal(text){var raw=String(text||''),matches=[],re=/\b(?:grand\s+)?total\s*[:$ ]+\$?([0-9]{1,5}[.,]\s?[0-9]{2})/ig,m;while((m=re.exec(raw)))matches.push(money(m[1].replace(/\s/g,'').replace(',','.')));if(matches.length)return matches[matches.length-1];var amounts=(raw.match(/\$?\d{1,5}[.,]\d{2}/g)||[]).map(function(v){return money(v.replace(',','.'));}).filter(Boolean);return amounts.length?Math.max.apply(Math,amounts):0;}
  function merchantFrom(text,fallback){var raw=String(text||''),known=['Walmart','Costco','WinCo Foods','Albertsons','Kroger','Safeway','Target','The Home Depot','Lowe’s','Amazon','Walgreens','CVS Pharmacy','Starbucks','Maverik','Shell','Chevron'];for(var i=0;i<known.length;i++)if(raw.toLowerCase().includes(known[i].toLowerCase().replace('’',"'"))||raw.toLowerCase().includes(known[i].toLowerCase()))return known[i];if(fallback&&String(fallback).trim())return String(fallback).trim();return'';}
  function contextFrom(input){var form=input&&input.closest&&input.closest('form'),data=readData(),accountIds=new Set((data.accounts||[]).map(function(a){return String(a.id);})),context={};if(!form)return context;var textInputs=Array.from(form.querySelectorAll('input[type="text"]'));context.merchant=(textInputs.find(function(el){return el.value&&el.value.trim().length>1;})||{}).value||'';var selects=Array.from(form.querySelectorAll('select'));var accountSelect=selects.find(function(el){return accountIds.has(String(el.value));});context.accountId=accountSelect&&accountSelect.value||'';return context;}
  function prepareImage(file){return new Promise(function(resolve){var img=new Image(),url=URL.createObjectURL(file);img.onload=function(){var scale=Math.min(3,2200/img.width),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));var ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,canvas.width,canvas.height);var image=ctx.getImageData(0,0,canvas.width,canvas.height),d=image.data;for(var i=0;i<d.length;i+=4){var gray=.299*d[i]+.587*d[i+1]+.114*d[i+2],v=gray>185?255:gray<70?0:Math.max(0,Math.min(255,(gray-128)*1.65+128));d[i]=d[i+1]=d[i+2]=v;}ctx.putImageData(image,0,0);URL.revokeObjectURL(url);canvas.toBlob(function(blob){resolve(blob||file);},'image/jpeg',.94);};img.onerror=function(){URL.revokeObjectURL(url);resolve(file);};img.src=url;});}
  function fileData(file){return new Promise(function(resolve,reject){var r=new FileReader();r.onload=function(){resolve(r.result);};r.onerror=reject;r.readAsDataURL(file);});}
  function compactReceiptData(file){return new Promise(function(resolve){var img=new Image(),objectUrl=URL.createObjectURL(file);img.onload=function(){var scale=Math.min(1,1000/img.width,1400/img.height),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(objectUrl);resolve(canvas.toDataURL('image/jpeg',.62));};img.onerror=function(){URL.revokeObjectURL(objectUrl);fileData(file).then(resolve,function(){resolve(null);});};img.src=objectUrl;});}
  function modalShell(){
    var old=document.getElementById('receiptScanReview');if(old)old.remove();var wrap=document.createElement('div');wrap.id='receiptScanReview';
    wrap.innerHTML='<div class="rs-backdrop"></div><section class="rs-panel" role="dialog" aria-modal="true" aria-label="Review receipt items"><div class="rs-head"><div><b>Receipt Item Review</b><span id="rsStatus">Reading receipt…</span></div><button id="rsClose" type="button">×</button></div><div id="rsBody" class="rs-body"><div class="rs-loading">Finding item names and prices…</div></div></section>';
    document.body.appendChild(wrap);wrap.querySelector('#rsClose').onclick=function(){wrap.remove();};return wrap;
  }
  function styles(){if(document.getElementById('receiptScannerStyles'))return;var s=document.createElement('style');s.id='receiptScannerStyles';s.textContent='#receiptScanReview{position:fixed;inset:0;z-index:2147483640;font-family:Inter,system-ui,sans-serif}.rs-backdrop{position:absolute;inset:0;background:rgba(15,23,42,.62)}.rs-panel{position:absolute;left:50%;top:4vh;transform:translateX(-50%);width:min(94vw,680px);max-height:92vh;overflow:auto;background:#fff;border-radius:18px;box-shadow:0 24px 70px rgba(0,0,0,.3)}.rs-head{position:sticky;top:0;z-index:2;display:flex;justify-content:space-between;align-items:start;padding:18px 20px;background:#fff;border-bottom:1px solid #e2e8f0}.rs-head b{display:block;font-size:19px;color:#1e293b}.rs-head span{display:block;margin-top:3px;font-size:12px;color:#64748b}.rs-head button{border:0;background:#f1f5f9;border-radius:8px;width:34px;height:34px;font-size:24px}.rs-body{padding:16px 20px 22px}.rs-loading{padding:34px;text-align:center;color:#64748b}.rs-fields{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:14px}.rs-fields label,.rs-item label{font-size:10px;text-transform:uppercase;color:#64748b;font-weight:700}.rs-fields input,.rs-fields select,.rs-item input,.rs-item select{width:100%;margin-top:4px;border:1px solid #cbd5e1;border-radius:8px;padding:9px;font-size:14px;background:#fff}.rs-item{display:grid;grid-template-columns:minmax(0,1fr) 155px 92px 30px;gap:8px;align-items:end;padding:10px 0;border-top:1px solid #e2e8f0}.rs-remove{height:38px;border:1px solid #fecaca;background:#fff;color:#dc2626;border-radius:8px}.rs-add,.rs-import{border:0;border-radius:9px;padding:11px 14px;font-weight:800}.rs-add{background:#eef2ff;color:#4338ca}.rs-import{float:right;background:#4f46e5;color:#fff}.rs-summary{margin-top:14px;padding-top:14px;border-top:2px solid #e2e8f0;font-weight:800}.rs-note{clear:both;padding-top:12px;font-size:11px;color:#64748b}@media(max-width:560px){.rs-panel{top:2vh;max-height:96vh}.rs-fields{grid-template-columns:1fr}.rs-item{grid-template-columns:1fr 1fr}.rs-remove{width:100%}}';document.head.appendChild(s);}
  function showReview(wrap,rows,text,dataUrl,context){
    var data=readData(),accounts=(data.accounts||[]).filter(function(a){return a.type!=='investment'&&a.type!=='loan';}),merchant=merchantFrom(text,context&&context.merchant),scannedTotal=receiptTotal(text),body=wrap.querySelector('#rsBody'),automatic=rows.length>0;if(!rows.length)rows.push({name:'Receipt item',price:scannedTotal||0,category:categoryFor(merchant+' '+text)});wrap.querySelector('#rsStatus').textContent=automatic?rows.length+' item'+(rows.length===1?'':'s')+' detected — verify before importing':'Automatic reading was unclear — complete the highlighted fields';
    body.innerHTML='<div class="rs-fields"><label>Vendor<input id="rsMerchant" value="'+escapeHtml(merchant)+'" placeholder="Enter vendor name"'+(!merchant?' autofocus':'')+'></label><label>Receipt amount<input id="rsScannedTotal" type="number" min="0" step="0.01" value="'+(scannedTotal?scannedTotal.toFixed(2):'')+'" placeholder="$0.00"></label><label>Account<select id="rsAccount">'+accounts.map(function(a){return'<option value="'+escapeHtml(a.id)+'"'+(context&&String(context.accountId)===String(a.id)?' selected':'')+'>'+escapeHtml(a.name)+'</option>';}).join('')+'</select></label><label>Date<input id="rsDate" type="date" value="'+today()+'"></label><label>Paid by<select id="rsPerson"><option>Joint</option><option>Michael</option><option>Cynthia</option></select></label></div><div id="rsItems"></div><button class="rs-add" id="rsAdd" type="button">+ Add item</button><button class="rs-import" id="rsImport" type="button">Import receipt items</button><div class="rs-summary">Itemized total: <span id="rsTotal">$0.00</span><div id="rsBreakdown"></div></div><div class="rs-note">Each item must have a category and price. If the scanner cannot read the receipt, enter the vendor and receipt amount, then edit or add item rows before importing.</div>';
    function options(selected){return CATEGORIES.map(function(c){return'<option'+(c===selected?' selected':'')+'>'+c+'</option>';}).join('');}
    function render(){var list=body.querySelector('#rsItems');list.innerHTML=rows.map(function(r,i){return'<div class="rs-item" data-i="'+i+'"><label>Item<input class="rs-name" value="'+escapeHtml(r.name)+'"></label><label>Category<select class="rs-category">'+options(r.category)+'</select></label><label>Price<input class="rs-price" type="number" min="0" step="0.01" value="'+r.price.toFixed(2)+'"></label><button class="rs-remove" type="button" aria-label="Remove item">×</button></div>';}).join('');sync();}
    function sync(){body.querySelectorAll('.rs-item').forEach(function(el){var i=+el.dataset.i;el.querySelector('.rs-name').oninput=function(e){rows[i].name=e.target.value;};el.querySelector('.rs-category').onchange=function(e){rows[i].category=e.target.value;};el.querySelector('.rs-price').oninput=function(e){rows[i].price=money(e.target.value);total();};el.querySelector('.rs-remove').onclick=function(){rows.splice(i,1);render();};});total();}
    function total(){body.querySelector('#rsTotal').textContent='$'+rows.reduce(function(sum,r){return sum+money(r.price);},0).toFixed(2);var totals={};rows.forEach(function(r){totals[r.category]=(totals[r.category]||0)+money(r.price);});body.querySelector('#rsBreakdown').innerHTML=Object.keys(totals).sort().map(function(cat){return'<div style="display:flex;justify-content:space-between;margin-top:6px;font-size:12px;color:#475569"><span>'+escapeHtml(cat)+'</span><b>$'+totals[cat].toFixed(2)+'</b></div>';}).join('');}
    body.querySelector('#rsScannedTotal').oninput=function(e){var entered=money(e.target.value);if(rows.length===1&&(rows[0].price===0||rows[0].name==='Receipt item')){rows[0].price=entered;render();}};
    body.querySelector('#rsAdd').onclick=function(){rows.push({name:'',category:'Shopping',price:0});render();};
    body.querySelector('#rsImport').onclick=function(){var clean=rows.filter(function(r){return r.name.trim()&&money(r.price)>0;});if(!clean.length){alert('Add at least one item with a price.');return;}var current=readData(),date=body.querySelector('#rsDate').value||today(),accountId=body.querySelector('#rsAccount').value||(current.accounts&&current.accounts[0]&&current.accounts[0].id)||'',person=body.querySelector('#rsPerson').value,store=body.querySelector('#rsMerchant').value.trim()||'Receipt purchase';current.transactions=current.transactions||[];var imported=clean.map(function(r,index){return{id:uid(),date:date,merchant:store+' — '+r.name.trim(),amount:-money(r.price),category:r.category,accountId:accountId,person:person,tags:['Receipt Scan'],tripId:'',notes:'Imported from itemized receipt',receipt:index===0?dataUrl:null,cleared:false,excludeFromBudget:false,needsReview:false};});current.transactions=imported.concat(current.transactions);var keptImage=true;try{localStorage.setItem(STORAGE,JSON.stringify(current));}catch(error){keptImage=false;imported.forEach(function(item){item.receipt=null;});try{localStorage.setItem(STORAGE,JSON.stringify(current));}catch(secondError){wrap.querySelector('#rsStatus').textContent='Import could not be saved because browser storage is full';alert('The Money app storage is full. Download a backup, then remove older receipt images before importing.');return;}}wrap.querySelector('#rsImport').disabled=true;wrap.querySelector('#rsStatus').textContent=clean.length+' receipt item'+(clean.length===1?'':'s')+' imported'+(keptImage?' with photo':' — photo omitted to save space');setTimeout(function(){location.reload();},850);};render();
  }
  async function scan(file,input){if(!file||!/^image\//.test(file.type||''))return;styles();var wrap=modalShell(),url=await compactReceiptData(file),context=contextFrom(input);if(!window.Tesseract){wrap.querySelector('#rsStatus').textContent='Receipt reader did not load';wrap.querySelector('#rsBody').innerHTML='<div class="rs-loading">Keep the photo attached and try again while connected to the internet.</div>';return;}var logger=function(m){if(m.status==='recognizing text')wrap.querySelector('#rsStatus').textContent='Reading receipt… '+Math.round((m.progress||0)*100)+'%';};try{var first=await Tesseract.recognize(file,'eng',{logger:logger}),firstText=first.data&&first.data.text||'',firstRows=parseReceipt(firstText),bestText=firstText,bestRows=firstRows;if(!firstRows.length&&!receiptTotal(firstText)){wrap.querySelector('#rsStatus').textContent='Trying an enhanced second scan…';var prepared=await prepareImage(file),second=await Tesseract.recognize(prepared,'eng',{logger:logger}),secondText=second.data&&second.data.text||'',secondRows=parseReceipt(secondText);if(secondRows.length>firstRows.length||receiptTotal(secondText)>0){bestText=secondText;bestRows=secondRows;}}showReview(wrap,bestRows,bestText,url,context);}catch(e){showReview(wrap,[],'',url,context);}}
  document.addEventListener('change',function(event){var input=event.target;if(!input||input.type!=='file'||!String(input.accept||'').includes('image'))return;var file=input.files&&input.files[0];if(file)setTimeout(function(){scan(file,input);},100);},true);
})();

